### ISSUE TITLE
Debian build not reading external hard drives

### ISSUE THREAD

**Issue by dilatedjux** [tkashkin/GameHub#568] opened 2021-08-27 18:03 UTC
Hey buddy, you're doing great work and I adore this software. There's just 1 issue: upon the Debian 11 Bullseye upgrade, the software no longer reads in from external ssd/hard drives from steam. I can still select where to install games from GOG, but with Steam it seems to only be able to read from the main hard drive. This worked on older versions of Debian and still works on Ubuntu. I'm looking to see if there is a way to read in from other hard disks as it was in previous versions.

Thank You for your hard work!
JP

**Comment by tkashkin** [comment] 2021-09-01 18:42
Duplicate of #558

**Closed by tkashkin** 2021-09-01 18:42 UTC
