### ISSUE TITLE
Allow multiple steam install folders

### ISSUE THREAD

**Issue by ChildishGiant** [tkashkin/GameHub#573] opened 2021-09-19 15:06 UTC
My games are all spread across 3 separate drives but currently GameHub only shows ones installed on my primary drive.
![image](https://user-images.githubusercontent.com/13716824/133932490-4ad91234-2462-457e-8503-9eae043a3540.png)

**Comment by ChildishGiant** [comment] 2021-09-19 15:11
This may be a regression due to the recent change to steam libraries. https://store.steampowered.com/oldnews/88497

**Comment by tkashkin** [comment] 2021-09-19 17:19
New Steam libraries should be supported since [`0.16.1`](https://github.com/tkashkin/GameHub/releases/tag/0.16.1-2-master). Let me know if it still doesn't work properly.

Duplicate of #558.

**Closed by tkashkin** 2021-09-19 17:19 UTC

**Comment by ChildishGiant** [comment] 2021-09-19 17:43
Ah I'm on `0.16.0-b98d07e-dev` since I'm using the PPA

**Comment by sonofevil** [comment] 2022-08-16 09:47
So, either I set the ~/.steam folder in the settings, in which case it works but no installed games are found, or I set my Steam library folder where I have all my games installed, in which case it says Steam config not found. I'm on 0.16.2.1-1
