### ISSUE TITLE
Merge games with different sources causes issues with user added games

### ISSUE THREAD

**Issue by dhollinger** [tkashkin/GameHub#282] opened 2019-07-09 19:38 UTC
###### Expected behavior
When `merge games with different sources` is enabled, I expect installed games (user added) to take priority over the uninstalled version and not change the custom banner/artwork.

Also, when merged the installed version should **always** have the highest priority and be launched from the unified tab.

example of unmerged user-added games:

![unmerged](https://user-images.githubusercontent.com/2914211/60916916-49778400-a255-11e9-98a6-0f7461537d7a.jpg)

###### Actual behavior
Several user-added games are hidden, listed as "Not Installed", and/or have artwork changed when merged with their Steam counterparts.

Additionally, when merged, user added games are not the primary launch option in the unified tab, instead Steam always take priority, regardless if the game is installed or not. User Added games should always take priority over other games OR be configurable.

Unified tab, Steam version takes priority over user added and changes artwork:
![merged_unified](https://user-images.githubusercontent.com/2914211/60917516-bfc8b600-a256-11e9-9656-093579133385.jpg)

User Added tab shows correct banner and launches correct version, but all the mission packs that were user added have been removed:
![merged_user_added](https://user-images.githubusercontent.com/2914211/60917551-d7a03a00-a256-11e9-8a09-4eba67498aa6.jpg)

In both cases, the Quake 1 and Quake 2 mission packs were hard removed from all tabs, while trying to launch the game in the unified tab will instead try to install the Steam version and launching from User added tab will launch the correct binary.

###### Steps to reproduce
Add a game manually that was installed to the system outside of GameHub/Steam/Lutris/etc, then turn on "Merge games with different sources".

###### Version and environment

```
Version: 0.14.1-aa1d50d-dev
Branch:  dev
Commit:  aa1d50d (aa1d50dd11dc0b8c7566fff044382d99f52bc7a3)
Distro:  Pop!_OS 19.04 (Ubuntu derivative, package from Pop!_OS repos)
DE:      pop:GNOME
```

**Comment by hlechner** [comment] 2019-07-09 23:13
Somehow I can't reproduce all issues because in my case the `user games` do not merge with the store ones, not sure if it's a bug on my side or what.

> User Added tab shows correct banner and launches correct version, but all the mission packs that were user added have been removed:

Seems the same issue I'm facing on this issue: #260, where the actual game is being merged with its DLC.

**Comment by tkashkin** [comment] 2019-07-10 20:09
@dhollinger is it better in 8ac1f27?

**Comment by dhollinger** [comment] 2019-07-11 21:16
I'll test it later today and let you know

**Comment by dhollinger** [comment] 2019-07-11 21:24
@tkashkin Still seeing the same issue on some occasions, when merged (I'll stick with my Quake example) the Base Quake games (1, 2, 3, 3 Team Arena) are now correctly displaying, but the Q1 and Q2 user added mission packs are listed as "Not Installed", have the art set to the steam version, and are missing entirely from the User added tab until I turn the merge option back off

**Comment by tkashkin** [comment] 2019-07-11 21:38
@dhollinger try to remove and readd them.

**Closed** 2019-08-31 17:00 UTC
