### ISSUE TITLE
Missing game titles

### ISSUE THREAD

**Issue by Seviraf** [tkashkin/GameHub#374] opened 2020-04-26 09:10 UTC
Following are listed in my Steam account but not Gamehub

- PyroMind
- MechCube: Escape
- What never was
- Flat Earths!

All except Pyromind are free so this is easy to test

- GameHub
    Version: 0.16.0-61d9d4e-dev
    Branch:  dev
    Commit:  61d9d4e523c322f1ae88963b5be88dc3dd5234c3
- Environment
    Distro:  Ubuntu Focal Fossa (development branch)
    DE:      ubuntu:GNOME
    GTK:     3.24.13
    Themes:  ChromeOS-Dark-Slate-3.36 | 1586516133331_Abyss-ENVY-Suru-GLOW

**Comment by tkashkin** [comment] 2020-05-17 08:16
Most likely duplicate of #349.

**Closed by tkashkin** 2020-05-17 08:16 UTC
