### ISSUE TITLE
Gamehub crashes on startup

### ISSUE THREAD

**Issue by MateuSai** [tkashkin/GameHub#643] opened 2022-06-21 08:59 UTC
Today I installed Gamehub for the first time. After connecting all the accounts, the app crashes all the time. It seems it is loading the game library, but after 2 seconds approximately, it crashes. This happens every time I try to open the application.

###### Steps to reproduce

Open Gamehub and after 2 seconds or so it crashes

###### Version and environment

```
- GameHub
    Version: 0.16.1--
    Branch:  
- Environment
    Distro:  Archcraft
    DE:      
    GTK:     3.24.34

```

###### GDB log

<details>
<summary>GDB log</summary>

```
Starting program: /usr/bin/gamehub 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffed7ff640 (LWP 56645)]
[New Thread 0x7fffecffe640 (LWP 56646)]

(gamehub:56639): Gtk-WARNING **: 10:50:52.495: Theme parsing error: gtk-contained-dark.css:2871:228: Missing closing bracket for :not()
[New Thread 0x7fffe7fff640 (LWP 56647)]
[Detaching after fork from child process 56648]
[Detaching after fork from child process 56649]
[Detaching after fork from child process 56650]
[Detaching after fork from child process 56651]
[Detaching after fork from child process 56652]
[Detaching after fork from child process 56653]
[INFO]   - GameHub
[INFO]       Version: 0.16.1--
[INFO]       Branch:
[INFO]   - Environment
[Detaching after fork from child process 56654]
[INFO]       Distro:  Archcraft
[INFO]       DE:
[INFO]       GTK:     3.24.34
[INFO]       Themes:  Adapta-Nokto | Archcraft-Dark

(gamehub:56639): Gtk-WARNING **: 10:50:52.957: Theme parsing error: gtk-contained-dark.css:2871:228: Missing closing bracket for :not()
[New Thread 0x7fffe77fe640 (LWP 56658)]
[New Thread 0x7fffe65ff640 (LWP 56659)]
[Thread 0x7fffe65ff640 (LWP 56659) exited]
[New Thread 0x7fffe65ff640 (LWP 56660)]
[New Thread 0x7fffe5dfe640 (LWP 56661)]
[Thread 0x7fffe65ff640 (LWP 56660) exited]
[New Thread 0x7fffe65ff640 (LWP 56662)]
[New Thread 0x7fffe55fd640 (LWP 56663)]
[Thread 0x7fffe5dfe640 (LWP 56661) exited]
[Thread 0x7fffe65ff640 (LWP 56662) exited]
[New Thread 0x7fffe65ff640 (LWP 56664)]
[Thread 0x7fffe55fd640 (LWP 56663) exited]
[New Thread 0x7fffe55fd640 (LWP 56665)]
[Thread 0x7fffe65ff640 (LWP 56664) exited]
[Thread 0x7fffe55fd640 (LWP 56665) exited]
[New Thread 0x7fffe55fd640 (LWP 56666)]
[New Thread 0x7fffe65ff640 (LWP 56667)]
[Thread 0x7fffe55fd640 (LWP 56666) exited]
[Thread 0x7fffe65ff640 (LWP 56667) exited]
[New Thread 0x7fffe65ff640 (LWP 56668)]
[New Thread 0x7fffe55fd640 (LWP 56669)]
[Thread 0x7fffe55fd640 (LWP 56669) exited]
[Thread 0x7fffe65ff640 (LWP 56668) exited]
[New Thread 0x7fffe55fd640 (LWP 56670)]
[New Thread 0x7fffe65ff640 (LWP 56671)]
[Thread 0x7fffe55fd640 (LWP 56670) exited]
[Thread 0x7fffe65ff640 (LWP 56671) exited]
[New Thread 0x7fffe65ff640 (LWP 56672)]
[New Thread 0x7fffe55fd640 (LWP 56673)]
[Detaching after fork from child process 56674]
[Detaching after fork from child process 56675]
[Thread 0x7fffe65ff640 (LWP 56672) exited]
[Thread 0x7fffe77fe640 (LWP 56658) exited]
[Detaching after fork from child process 56698]
[New Thread 0x7fffe77fe640 (LWP 56700)]
[New Thread 0x7fffe65ff640 (LWP 56701)]
[Thread 0x7fffe77fe640 (LWP 56700) exited]
[Thread 0x7fffe65ff640 (LWP 56701) exited]
[New Thread 0x7fffe65ff640 (LWP 56703)]
[New Thread 0x7fffe77fe640 (LWP 56704)]
[New Thread 0x7fffe5dfe640 (LWP 56705)]
[New Thread 0x7fffcbfff640 (LWP 56706)]
[New Thread 0x7fffcb7fe640 (LWP 56707)]
[New Thread 0x7fffcaffd640 (LWP 56708)]
[New Thread 0x7fffca7fc640 (LWP 56709)]
[New Thread 0x7fffc9ffb640 (LWP 56710)]
[New Thread 0x7fffc97fa640 (LWP 56711)]
[FATAL]  [Json] json_object_get_string_member: assertion 'node != NULL' failed
[FATAL]  [Json] json_object_get_string_member: assertion 'node != NULL' failed
[FATAL]  [Json] json_object_get_string_member: assertion 'node != NULL' failed
[FATAL]  [Json] json_object_get_string_member: assertion 'node != NULL' failed
[FATAL]  [Json] json_object_get_string_member: assertion 'node != NULL' failed
[FATAL]  [Json] json_object_get_string_member: assertion 'node != NULL' failed
[INFO]   [ButlerClient: log] Fetching fresh data...
[INFO]   [ButlerClient: log] Fetching page 1
[New Thread 0x7fffc8ff9640 (LWP 56713)]
[New Thread 0x7fffabfff640 (LWP 56714)]
[New Thread 0x7fffab7fe640 (LWP 56715)]
[New Thread 0x7fffaaffd640 (LWP 56716)]
[Thread 0x7fffab7fe640 (LWP 56715) exited]
[New Thread 0x7fffab7fe640 (LWP 56717)]
[New Thread 0x7fffaa7fc640 (LWP 56718)]
[Thread 0x7fffaaffd640 (LWP 56716) exited]
[Thread 0x7fffab7fe640 (LWP 56717) exited]
[Thread 0x7fffaa7fc640 (LWP 56718) exited]
[New Thread 0x7fffaa7fc640 (LWP 56721)]
[New Thread 0x7fffab7fe640 (LWP 56722)]
[Thread 0x7fffaa7fc640 (LWP 56721) exited]
[Thread 0x7fffab7fe640 (LWP 56722) exited]
[New Thread 0x7fffab7fe640 (LWP 56723)]
[New Thread 0x7fffaa7fc640 (LWP 56724)]
[Thread 0x7fffab7fe640 (LWP 56723) exited]
[New Thread 0x7fffab7fe640 (LWP 56725)]
[Thread 0x7fffaa7fc640 (LWP 56724) exited]
[New Thread 0x7fffaa7fc640 (LWP 56726)]
[Thread 0x7fffab7fe640 (LWP 56725) exited]
[Thread 0x7fffaa7fc640 (LWP 56726) exited]
[Thread 0x7fffe5dfe640 (LWP 56705) exited]
[Thread 0x7fffc9ffb640 (LWP 56710) exited]
[Thread 0x7fffe55fd640 (LWP 56673) exited]
[Thread 0x7fffc8ff9640 (LWP 56713) exited]
[Thread 0x7fffabfff640 (LWP 56714) exited]
[Thread 0x7fffe77fe640 (LWP 56704) exited]
[Thread 0x7fffe65ff640 (LWP 56703) exited]
[Thread 0x7fffcaffd640 (LWP 56708) exited]

Thread 29 "pool-gamehub" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffca7fc640 (LWP 56709)]
0x00005555556041d0 in __lambda48_ (_data21_=0x55555b83fb80) at ../src/data/sources/humble/Trove.vala:89
89	../src/data/sources/humble/Trove.vala: No such file or directory.
```

</details>

**Comment by tkashkin** [comment] 2022-06-21 12:31
Duplicate of #611.

Update to [0.16.2](https://github.com/tkashkin/GameHub/releases/tag/0.16.2-1-dev) or newer or disable Humble Trove support with:
```
gsettings set com.github.tkashkin.gamehub.auth.humble load-trove-games false
```

**Closed as completed by tkashkin** 2022-06-21 12:31 UTC
