### ISSUE TITLE
GameHub not finding a specific steam game

### ISSUE THREAD

**Issue by ccrowles** [tkashkin/GameHub#433] opened 2020-10-19 10:57 UTC
###### Expected behavior
GameHub listing in the library the game Scarlet Hollow, since it shows as installed both on Steam and on Lutris, it's in the default Steam installation directory (like all the other steam games) and is playable without issues.

###### Actual behavior
GameHub loads my entire Steam library except for Scarlet Hollow.

###### Steps to reproduce
Install [Scarlet Hollow](https://store.steampowered.com/app/1406040/Scarlet_Hollow/) (it's free) from Steam client.
Open GameHub.
Wait for GameHub to update the steam library catalog.
Search for Scarlet Hollow.

###### Version and environment

```
- GameHub
    Version: 0.16.0-b037170-dev
    Branch:  dev
    Commit:  b037170fb4c4d8bc7d6d43ff424ec37ac52d7718
- Environment
    Distro:  Ubuntu 20.04.1 LTS
    DE:      KDE
    GTK:     3.24.20
    Themes:  Sweet-Dark | candy-icons
```

**Comment by tkashkin** [comment] 2020-10-19 11:26
Probably duplicate of #349.

I plan to implement automatic import of installed games and option to add a game by appid.

**Closed by tkashkin** 2020-10-19 11:26 UTC
